[package]
name = "bombuscv-buttons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.13.1"
nix = "0.24.2"
procfs = "0.14.0"
